<?php
/**
 * BBS NetAxept, Norge
 *
 * LICENSE AND USAGE INFORMATION
 * It is NOT allowed to modify, copy or re-sell this file or any 
 * part of it. Please contact us by email at post@trollweb.no or 
 * visit us at www.trollweb.no/bbs if you have any questions about this.
 * Trollweb is not responsible for any problems caused by this file.
 *
 * Visit us at http://www.trollweb.no today!
 * 
 * @category   Trollweb
 * @package    Trollweb_BBSNetAxept
 * @copyright  Copyright (c) 2009 Trollweb (http://www.trollweb.no)
 * @license    Single-site License
 * 
 */
?>
<?php echo Mage::helper('payment')->__('Transaction id: %s', $this->htmlEscape($this->getInfo()->getBbsTransactionId())) ?><br/>
<?php echo Mage::helper('payment')->__('Authorization id: %s', $this->htmlEscape($this->getInfo()->getBbsAuthorizationId())) ?><br/>
<?php echo Mage::helper('payment')->__('Authenticated status: %s', $this->htmlEscape($this->getInfo()->getBbsAuthenticatedStatus())) ?><br/>
<?php echo Mage::helper('payment')->__('Authenticated with: %s', $this->htmlEscape($this->getInfo()->getBbsAuthenticatedWith())) ?><br/>
<?php echo Mage::helper('payment')->__('Issuer: %s', $this->htmlEscape($this->getInfo()->getBbsIssuerId())) ?><br/>
<?php echo Mage::helper('payment')->__('Issuer country: %s', $this->htmlEscape($this->getInfo()->getBbsIssuerCountry())) ?><br/>
<?php echo Mage::helper('payment')->__('Payment status: %s', $this->htmlEscape($this->getInfo()->getStatus())) ?><br/>